spring:
  redis:
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}
  cache:
    type: redis
    redis:
      time-to-live: PT60M
  data:
    mongodb:
      auto-index-creation: true
#      uri: mongodb://admin:admin@localhost:27017/offers
      uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DB_NAME}


  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

offer:
  http:
    client:
      config:
        connectionTimeout: 1000
        port: 5057
        readTimeout: 1000
        uri: http://ec2-3-120-147-150.eu-central-1.compute.amazonaws.com


http:
  offers:
    scheduler:
      request:
        delay: PT120S


scheduling:
  enabled: true


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true


auth:
  jwt:
    secret: ${JWT_SECRET}
    issuer: job-offers-backend
    expirationDays: 30